<a href="https://colab.research.google.com/github/NileshCT/Machine_Learning_Models/blob/main/Decision_Tree_classification_modelling_weatheraus_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing required libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [4]:
df=pd.read_csv("/content/drive/MyDrive/weatherAUS.csv.zip")

In [5]:
df.drop(["Date"],axis=1,inplace=True)

In [6]:
numeric_feature=df.describe(include=float).columns
numeric_feature

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm'],
      dtype='object')

In [7]:
#Exploring all numeric_features from dataframe.
categorical_feature=df.describe(include=object).columns
categorical_feature

Index(['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday',
       'RainTomorrow'],
      dtype='object')

In [8]:
#Creating new dataframe by cloning df dataframe.
df1=df.copy()

In [9]:
a=[(i,index) for i,index in enumerate(df["RainTomorrow"]) if pd.isna(index)]
result = pd.DataFrame(a).set_index(0)

**Extracting inferencial data**

In [10]:
t=pd.DataFrame(a).set_index(0)
t.head()

1
0      
14  NaN
283 NaN
435 NaN
437 NaN
443 NaN

In [11]:
t.shape

(3267, 1)

In [12]:
index_nan=t.index.tolist()
index_nan

[14,
 283,
 435,
 437,
 443,
 452,
 455,
 464,
 611,
 983,
 984,
 985,
 986,
 1013,
 1374,
 1529,
 1530,
 1531,
 1685,
 1922,
 2031,
 2032,
 2033,
 2042,
 2913,
 2934,
 2942,
 2943,
 2944,
 3201,
 3211,
 3316,
 3338,
 3339,
 3384,
 3411,
 3412,
 3428,
 3433,
 3438,
 3446,
 3447,
 3452,
 3457,
 3462,
 3471,
 3472,
 3482,
 3517,
 3524,
 3525,
 3526,
 3529,
 3530,
 3532,
 3539,
 3542,
 3549,
 3552,
 3576,
 3584,
 3595,
 3629,
 3634,
 3639,
 3692,
 3760,
 3955,
 4044,
 4050,
 4131,
 4344,
 4345,
 4629,
 4644,
 4656,
 4845,
 4900,
 4911,
 4912,
 4935,
 4938,
 4939,
 5056,
 5079,
 5149,
 5393,
 5458,
 5459,
 5460,
 5461,
 5462,
 5841,
 5842,
 5843,
 5844,
 5845,
 5846,
 5847,
 5848,
 5849,
 5850,
 5851,
 5852,
 5853,
 5854,
 5855,
 5856,
 5857,
 5876,
 6294,
 6968,
 6969,
 6970,
 7446,
 7447,
 8529,
 8530,
 8588,
 8838,
 8839,
 8840,
 8841,
 8842,
 8843,
 8847,
 8848,
 8849,
 8904,
 8905,
 8906,
 9147,
 10238,
 10448,
 10534,
 10816,
 10820,
 10821,
 10822,
 10920,
 10921,
 10922,
 10923,
 1

In [13]:
df1_inference=df1.iloc[index_nan]
df1_inference

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
14       Albury      8.4     24.6       0.0          NaN       NaN   
283      Albury      2.6      NaN       0.0          NaN       NaN   
435      Albury     22.1     35.1       0.0          NaN       NaN   
437      Albury     21.5     35.0       0.0          NaN       NaN   
443      Albury     15.5     30.6       0.0          NaN       NaN   
...         ...      ...      ...       ...          ...       ...   
144955    Uluru     22.5     37.7       0.0          NaN       NaN   
145091    Uluru     12.3     19.1       0.0          NaN       NaN   
145092    Uluru     14.2     18.7       NaN          NaN       NaN   
145335    Uluru     13.5      NaN       0.0          NaN       NaN   
145459    Uluru     14.9      NaN       0.0          NaN       NaN   

       WindGustDir  WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  \
14             NaN            NaN          S        WNW  ...         57.0   
283            NaN            NaN          E        WNW  ...         71.0   
435            NaN            NaN        ENE         SW  ...         58.0   
437            NaN            NaN        SSE          E  ...         76.0   
443            NaN            NaN         SE        SSW  ...         66.0   
...            ...            ...        ...        ...  ...          ...   
144955          SE           50.0         SE        ESE  ...         22.0   
145091         NaN            NaN        NaN        NaN  ...         79.0   
145092         NaN            NaN          W        NaN  ...         81.0   
145335         NaN            NaN        ENE         SW  ...         23.0   
145459         NaN            NaN        ESE        ESE  ...         62.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
14             32.0       1009.7       1008.7       NaN       NaN     15.9   
283            55.0       1017.8       1017.6       NaN       6.0      9.7   
435            37.0       1020.9       1017.8       NaN       1.0     26.9   
437            35.0       1015.8       1010.3       NaN       8.0     24.2   
443            30.0       1015.9       1013.8       NaN       NaN     19.4   
...             ...          ...          ...       ...       ...      ...   
144955         11.0       1012.6       1009.6       NaN       NaN     28.8   
145091         62.0       1016.8       1014.1       8.0       8.0     15.6   
145092         67.0       1015.2       1014.6       8.0       8.0     16.6   
145335         11.0       1013.7       1008.4       NaN       NaN     25.2   
145459         36.0       1020.2       1017.9       8.0       8.0     15.0   

        Temp3pm  RainToday  RainTomorrow  
14         23.5         No           NaN  
283        14.3         No           NaN  
435        33.5         No           NaN  
437        33.1         No           NaN  
443        30.0         No           NaN  
...         ...        ...           ...  
144955     37.2         No           NaN  
145091     18.9         No           NaN  
145092     17.5        NaN           NaN  
145335     34.4         No           NaN  
145459     20.9         No           NaN  

[3267 rows x 22 columns]

In [14]:
#Creating list of all non null values in the target variable for spliting in train and test data.
a=[]
for i in range(df1.shape[0]):
  if i not in index_nan:
    a.append(i)

**Separating known data**

In [15]:
df_Known_data=df.iloc[a]
df_Known_data

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0        Albury     13.4     22.9       0.6          NaN       NaN   
1        Albury      7.4     25.1       0.0          NaN       NaN   
2        Albury     12.9     25.7       0.0          NaN       NaN   
3        Albury      9.2     28.0       0.0          NaN       NaN   
4        Albury     17.5     32.3       1.0          NaN       NaN   
...         ...      ...      ...       ...          ...       ...   
145454    Uluru      3.5     21.8       0.0          NaN       NaN   
145455    Uluru      2.8     23.4       0.0          NaN       NaN   
145456    Uluru      3.6     25.3       0.0          NaN       NaN   
145457    Uluru      5.4     26.9       0.0          NaN       NaN   
145458    Uluru      7.8     27.0       0.0          NaN       NaN   

       WindGustDir  WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  \
0                W           44.0          W        WNW  ...         71.0   
1              WNW           44.0        NNW        WSW  ...         44.0   
2              WSW           46.0          W        WSW  ...         38.0   
3               NE           24.0         SE          E  ...         45.0   
4                W           41.0        ENE         NW  ...         82.0   
...            ...            ...        ...        ...  ...          ...   
145454           E           31.0        ESE          E  ...         59.0   
145455           E           31.0         SE        ENE  ...         51.0   
145456         NNW           22.0         SE          N  ...         56.0   
145457           N           37.0         SE        WNW  ...         53.0   
145458          SE           28.0        SSE          N  ...         51.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0              22.0       1007.7       1007.1       8.0       NaN     16.9   
1              25.0       1010.6       1007.8       NaN       NaN     17.2   
2              30.0       1007.6       1008.7       NaN       2.0     21.0   
3              16.0       1017.6       1012.8       NaN       NaN     18.1   
4              33.0       1010.8       1006.0       7.0       8.0     17.8   
...             ...          ...          ...       ...       ...      ...   
145454         27.0       1024.7       1021.2       NaN       NaN      9.4   
145455         24.0       1024.6       1020.3       NaN       NaN     10.1   
145456         21.0       1023.5       1019.1       NaN       NaN     10.9   
145457         24.0       1021.0       1016.8       NaN       NaN     12.5   
145458         24.0       1019.4       1016.5       3.0       2.0     15.1   

        Temp3pm  RainToday  RainTomorrow  
0          21.8         No            No  
1          24.3         No            No  
2          23.2         No            No  
3          26.5         No            No  
4          29.7         No            No  
...         ...        ...           ...  
145454     20.9         No            No  
145455     22.4         No            No  
145456     24.5         No            No  
145457     26.1         No            No  
145458     26.0         No            No  

[142193 rows x 22 columns]

**Missing values tratment for known data**

In [16]:
df_Known_data=df_Known_data.fillna(method="bfill",axis=0).fillna(method="ffill",axis=0)
df_Known_data

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0        Albury     13.4     22.9       0.6         12.0      12.3   
1        Albury      7.4     25.1       0.0         12.0      12.3   
2        Albury     12.9     25.7       0.0         12.0      12.3   
3        Albury      9.2     28.0       0.0         12.0      12.3   
4        Albury     17.5     32.3       1.0         12.0      12.3   
...         ...      ...      ...       ...          ...       ...   
145454    Uluru      3.5     21.8       0.0          6.4      10.7   
145455    Uluru      2.8     23.4       0.0          6.4      10.7   
145456    Uluru      3.6     25.3       0.0          6.4      10.7   
145457    Uluru      5.4     26.9       0.0          6.4      10.7   
145458    Uluru      7.8     27.0       0.0          6.4      10.7   

       WindGustDir  WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  \
0                W           44.0          W        WNW  ...         71.0   
1              WNW           44.0        NNW        WSW  ...         44.0   
2              WSW           46.0          W        WSW  ...         38.0   
3               NE           24.0         SE          E  ...         45.0   
4                W           41.0        ENE         NW  ...         82.0   
...            ...            ...        ...        ...  ...          ...   
145454           E           31.0        ESE          E  ...         59.0   
145455           E           31.0         SE        ENE  ...         51.0   
145456         NNW           22.0         SE          N  ...         56.0   
145457           N           37.0         SE        WNW  ...         53.0   
145458          SE           28.0        SSE          N  ...         51.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0              22.0       1007.7       1007.1       8.0       2.0     16.9   
1              25.0       1010.6       1007.8       7.0       2.0     17.2   
2              30.0       1007.6       1008.7       7.0       2.0     21.0   
3              16.0       1017.6       1012.8       7.0       8.0     18.1   
4              33.0       1010.8       1006.0       7.0       8.0     17.8   
...             ...          ...          ...       ...       ...      ...   
145454         27.0       1024.7       1021.2       3.0       2.0      9.4   
145455         24.0       1024.6       1020.3       3.0       2.0     10.1   
145456         21.0       1023.5       1019.1       3.0       2.0     10.9   
145457         24.0       1021.0       1016.8       3.0       2.0     12.5   
145458         24.0       1019.4       1016.5       3.0       2.0     15.1   

        Temp3pm  RainToday  RainTomorrow  
0          21.8         No            No  
1          24.3         No            No  
2          23.2         No            No  
3          26.5         No            No  
4          29.7         No            No  
...         ...        ...           ...  
145454     20.9         No            No  
145455     22.4         No            No  
145456     24.5         No            No  
145457     26.1         No            No  
145458     26.0         No            No  

[142193 rows x 22 columns]

**known data splitting for further scaling. i am not appling the scaling on the target feature**

In [17]:
x_known=df_Known_data.drop(["RainTomorrow"],axis=1)
y_known=df_Known_data["RainTomorrow"]

**lebal encoding on x_known data**

In [18]:
#Label encoding on known data
from sklearn import preprocessing
L_Encoder=preprocessing.LabelEncoder()
x_known["Location"]=L_Encoder.fit_transform(x_known["Location"])

In [19]:
x_known["Location"].unique()

array([ 2,  4, 10, 11, 21, 24, 26, 27, 30, 34, 37, 38, 42, 45, 47,  9, 40,
       23,  5,  6, 35, 19, 18, 20, 25, 33, 44, 12,  7,  8, 14, 39,  0, 22,
       28, 48,  1, 46, 29, 32, 31, 36, 43, 15, 17,  3, 13, 16, 41])

In [20]:
x_known["WindGustDir"]=L_Encoder.fit_transform(x_known["WindGustDir"])

In [21]:
x_known["WindDir9am"]=L_Encoder.fit_transform(x_known["WindDir9am"])

In [22]:
x_known["WindDir3pm"]=L_Encoder.fit_transform(x_known["WindDir3pm"])

In [23]:
x_known["RainToday"]=L_Encoder.fit_transform(x_known["RainToday"])

In [24]:
x_known.head()

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustDir  \
0         2     13.4     22.9       0.6         12.0      12.3           13   
1         2      7.4     25.1       0.0         12.0      12.3           14   
2         2     12.9     25.7       0.0         12.0      12.3           15   
3         2      9.2     28.0       0.0         12.0      12.3            4   
4         2     17.5     32.3       1.0         12.0      12.3           13   

   WindGustSpeed  WindDir9am  WindDir3pm  ...  WindSpeed3pm  Humidity9am  \
0           44.0          13          14  ...          24.0         71.0   
1           44.0           6          15  ...          22.0         44.0   
2           46.0          13          15  ...          26.0         38.0   
3           24.0           9           0  ...           9.0         45.0   
4           41.0           1           7  ...          20.0         82.0   

   Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0         22.0       1007.7       1007.1       8.0       2.0     16.9   
1         25.0       1010.6       1007.8       7.0       2.0     17.2   
2         30.0       1007.6       1008.7       7.0       2.0     21.0   
3         16.0       1017.6       1012.8       7.0       8.0     18.1   
4         33.0       1010.8       1006.0       7.0       8.0     17.8   

   Temp3pm  RainToday  
0     21.8          0  
1     24.3          0  
2     23.2          0  
3     26.5          0  
4     29.7          0  

[5 rows x 21 columns]

**scaling on x_known data**

In [25]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
model=scalar.fit(x_known)
x_known1=model.transform(x_known)
print(x_known1)

[[-1.5270045   0.18911965 -0.0462377  ... -0.00962269  0.00708313
  -0.54029965]
 [-1.5270045  -0.74794986  0.26286199 ...  0.03643231  0.36734324
  -0.54029965]
 [-1.5270045   0.11103052  0.3471619  ...  0.61979554  0.20882879
  -0.54029965]
 ...
 [ 1.21224943 -1.34142722  0.29096196 ... -0.93072252  0.39616405
  -0.54029965]
 [ 1.21224943 -1.06030637  0.51576173 ... -0.6850959   0.62673052
  -0.54029965]
 [ 1.21224943 -0.68547856  0.52981172 ... -0.28595264  0.61232012
  -0.54029965]]


In [26]:
x_known2=pd.DataFrame(x_known1)

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x_known2,y_known,random_state=0,test_size=0.20)

In [74]:
from sklearn.tree import DecisionTreeClassifier 
model = DecisionTreeClassifier() 
decision_tree=model.fit (X_train, y_train) 
predictions_train = model.predict(X_train)

In [76]:
#Measure the performance of the decision tree model
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(classification_report(y_train, predictions_train))
print(confusion_matrix(y_train, predictions_train))

              precision    recall  f1-score   support

          No       1.00      1.00      1.00     88249
         Yes       1.00      1.00      1.00     25505

    accuracy                           1.00    113754
   macro avg       1.00      1.00      1.00    113754
weighted avg       1.00      1.00      1.00    113754

[[88249     0]
 [    4 25501]]


In [77]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_train,predictions_train)
score

0.9999648364013574

In [78]:
predictions_test = model.predict(X_test)

In [79]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test,predictions_test)
score

0.7861739161011287

**predict_proba method ok known data**

In [80]:
# probability of getting output as 0 - no rain
model.predict_proba(X_train)[:,0]

array([1., 1., 1., ..., 1., 1., 0.])

In [81]:
# probability of getting output as 0 - rain
model.predict_proba(X_train)[:,1]

array([0., 0., 0., ..., 0., 0., 1.])

In [38]:
df1_inference.head(10)

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
14    Albury      8.4     24.6       0.0          NaN       NaN         NaN   
283   Albury      2.6      NaN       0.0          NaN       NaN         NaN   
435   Albury     22.1     35.1       0.0          NaN       NaN         NaN   
437   Albury     21.5     35.0       0.0          NaN       NaN         NaN   
443   Albury     15.5     30.6       0.0          NaN       NaN         NaN   
452   Albury     17.2      NaN       0.0          NaN       NaN         NaN   
455   Albury     14.4      NaN       0.0          NaN       NaN         NaN   
464   Albury      8.8      NaN       0.0          NaN       NaN         NaN   
611   Albury      1.2      9.6       0.0          NaN       NaN         NaN   
983   Albury      4.0      NaN       0.2          NaN       NaN         NaN   

     WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
14             NaN          S        WNW  ...         57.0         32.0   
283            NaN          E        WNW  ...         71.0         55.0   
435            NaN        ENE         SW  ...         58.0         37.0   
437            NaN        SSE          E  ...         76.0         35.0   
443            NaN         SE        SSW  ...         66.0         30.0   
452            NaN         NE          E  ...         54.0         28.0   
455            NaN         SE        SSE  ...         50.0         35.0   
464            NaN        SSE        SSE  ...         69.0         35.0   
611            NaN        NaN          N  ...         94.0         71.0   
983            NaN          W        WSW  ...         79.0         47.0   

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
14        1009.7       1008.7       NaN       NaN     15.9     23.5   
283       1017.8       1017.6       NaN       6.0      9.7     14.3   
435       1020.9       1017.8       NaN       1.0     26.9     33.5   
437       1015.8       1010.3       NaN       8.0     24.2     33.1   
443       1015.9       1013.8       NaN       NaN     19.4     30.0   
452       1024.6       1020.7       NaN       NaN     20.6     29.2   
455       1018.5       1016.2       6.0       NaN     17.1     25.5   
464       1023.7       1023.0       NaN       1.0     12.5     21.8   
611       1019.8       1017.0       8.0       8.0      5.5      9.2   
983       1015.9       1013.8       NaN       NaN      9.3     15.6   

     RainToday  RainTomorrow  
14          No           NaN  
283         No           NaN  
435         No           NaN  
437         No           NaN  
443         No           NaN  
452         No           NaN  
455         No           NaN  
464         No           NaN  
611         No           NaN  
983         No           NaN  

[10 rows x 22 columns]

**Spliting data of inferenceial data**


In [39]:
x_inference=df1_inference.drop(["RainTomorrow"],axis=1)
y_inference=df1_inference["RainTomorrow"]

In [40]:
x_inference.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3267 entries, 14 to 145459
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Location       3267 non-null   object 
 1   MinTemp        2419 non-null   float64
 2   MaxTemp        2328 non-null   float64
 3   Rainfall       1412 non-null   float64
 4   Evaporation    1320 non-null   float64
 5   Sunshine       1248 non-null   float64
 6   WindGustDir    2271 non-null   object 
 7   WindGustSpeed  2274 non-null   float64
 8   WindDir9am     2714 non-null   object 
 9   WindDir3pm     2817 non-null   object 
 10  WindSpeed9am   2848 non-null   float64
 11  WindSpeed3pm   2835 non-null   float64
 12  Humidity9am    2387 non-null   float64
 13  Humidity3pm    2370 non-null   float64
 14  Pressure9am    2216 non-null   float64
 15  Pressure3pm    2220 non-null   float64
 16  Cloud9am       1036 non-null   float64
 17  Cloud3pm       1003 non-null   float64
 18  Temp9

In [41]:
#Label encoding on known data
from sklearn import preprocessing
L_Encoder=preprocessing.LabelEncoder()
x_inference["Location"]=L_Encoder.fit_transform(x_inference["Location"])

In [42]:
x_inference["Location"].unique()

array([ 2,  4, 10, 11, 20, 23, 25, 26, 29, 31, 34, 35, 39, 42, 44,  9, 37,
       22,  5,  6, 32, 18, 19, 24, 30, 41, 12,  7,  8, 14, 36,  0, 21, 27,
       45,  1, 43, 28, 33, 40, 15, 17,  3, 13, 16, 38])

In [43]:
x_inference["WindGustDir"]=L_Encoder.fit_transform(x_inference["WindGustDir"])

In [44]:
x_inference["WindDir9am"]=L_Encoder.fit_transform(x_inference["WindDir9am"])

In [45]:
x_inference["WindDir3pm"]=L_Encoder.fit_transform(x_inference["WindDir3pm"])

In [46]:
x_inference["RainToday"]=L_Encoder.fit_transform(x_inference["RainToday"])

**Missing value treatment of inference data**

In [48]:
x_inference=x_inference.fillna(method="bfill",axis=0).fillna(method="ffill",axis=0)

**Scaling on inferencial data**

In [49]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
model=scalar.fit(x_inference)
x_inference1=model.transform(x_inference)
print(x_inference1)

[[-1.83604947 -0.37644162  0.42089382 ...  0.06989278  0.49797963
  -1.41568169]
 [-1.83604947 -1.22707146  1.92729804 ... -0.84064631 -0.86315775
  -1.41568169]
 [-1.83604947  1.63280473  1.92729804 ...  1.68536535  1.97747677
  -1.41568169]
 ...
 [ 1.05504262  0.47418823 -0.42556188 ...  0.17269558 -0.38971866
   0.82133504]
 [ 1.05504262  0.371526   -0.42556188 ...  1.43570141  2.11063152
  -1.41568169]
 [ 1.05504262  0.57685045 -0.42556188 ... -0.06228225  0.11331037
  -1.41568169]]


In [51]:
x_inference2=pd.DataFrame(x_inference1)

In [52]:
x_inference2

0         1         2        3         4         5         6   \
0    -1.836049 -0.376442  0.420894 -0.37223  0.232543 -1.852555  1.041038   
1    -1.836049 -1.227071  1.927298 -0.37223  0.232543 -1.852555  1.041038   
2    -1.836049  1.632805  1.927298 -0.37223  0.232543 -1.852555  1.041038   
3    -1.836049  1.544809  1.912951 -0.37223  0.232543 -1.852555  1.041038   
4    -1.836049  0.664847  1.281696 -0.37223  0.232543 -1.852555  1.041038   
...        ...       ...       ...      ...       ...       ...       ...   
3262  1.055043  1.691469  2.300312 -0.37223  1.022158  0.301435 -0.286912   
3263  1.055043  0.195534 -0.368175 -0.37223  1.022158  0.301435  1.041038   
3264  1.055043  0.474188 -0.425562 -0.37223  1.022158  0.301435  1.041038   
3265  1.055043  0.371526 -0.425562 -0.37223  1.022158  0.301435  1.041038   
3266  1.055043  0.576850 -0.425562 -0.37223  1.022158  0.301435  1.041038   

            7         8         9   ...        11        12        13  \
0    -0.911285 -0.223650  0.968545  ...  1.174040 -0.967107 -1.004002   
1    -0.911285 -1.758660  0.968545  ... -0.668638 -0.153482  0.080009   
2    -0.911285 -1.566784  0.563782  ... -0.885424 -0.908991 -0.768348   
3    -0.911285  0.160102 -1.864798  ... -1.318995  0.137098 -0.862610   
4    -0.911285 -0.031774  0.361400  ... -0.885424 -0.444062 -1.098264   
...        ...       ...       ...  ...       ...       ...       ...   
3262  0.448463 -0.031774 -1.460034  ...  0.740469 -3.001169 -1.993752   
3263  0.448463  1.311360  1.373308  ... -1.318995  0.311447  0.409925   
3264  0.448463  0.735731  1.373308  ... -1.318995  0.427679  0.645580   
3265  0.448463 -1.566784  0.563782  ... -1.318995 -2.943053 -1.993752   
3266  0.448463 -1.374907 -1.460034  ... -0.235067 -0.676527 -0.815479   

            14        15        16        17        18        19        20  
0    -1.233469 -1.088440  0.415128  0.564497  0.069893  0.497980 -1.415682  
1    -0.096915  0.220424  0.415128  0.564497 -0.840646 -0.863158 -1.415682  
2     0.338062  0.249837  0.415128 -1.376370  1.685365  1.977477 -1.415682  
3    -0.377546 -0.853138  0.415128  1.340844  1.288840  1.918297 -1.415682  
4    -0.363514 -0.338417  0.415128 -1.376370  0.583907  1.459653 -1.415682  
...        ...       ...       ...       ...       ...       ...       ...  
3262 -0.826555 -0.956083  1.090874  1.340844  1.964402  2.524891 -1.415682  
3263 -0.237230 -0.294298  1.090874  1.340844  0.025834 -0.182589 -1.415682  
3264 -0.461735 -0.220766  1.090874  1.340844  0.172696 -0.389719  0.821335  
3265 -0.672208 -1.132558  1.090874  1.340844  1.435701  2.110632 -1.415682  
3266  0.239842  0.264543  1.090874  1.340844 -0.062282  0.113310 -1.415682  

[3267 rows x 21 columns]

In [53]:
x_inference2=pd.DataFrame(x_inference1)

In [91]:
predictions_infer_test = model.predict(X_test1)

In [92]:
predictions_infer_test1=pd.DataFrame(predictions_infer_test)
predictions_infer_test1

0
0     No
1     No
2    Yes
3     No
4     No
..   ...
812   No
813  Yes
814   No
815  Yes
816  Yes

[817 rows x 1 columns]

In [58]:
y_pred_test1 = logreg.predict(X_test1)

y_pred_test1

array(['No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No',
       'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No',
       'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No',
       'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'

In [59]:
y_pred_test2=pd.DataFrame(y_pred_test1)
# y_pred_test2
y_pred_test2

0
0    No
1    No
2    No
3    No
4    No
..   ..
649  No
650  No
651  No
652  No
653  No

[654 rows x 1 columns]

**# probability of getting output as 0 - no rain**

In [60]:
# probability of getting output as 0 - no rain

logreg.predict_proba(X_train1)[:,0]

array([0.79494582, 0.93464019, 0.92323421, ..., 0.96324642, 0.73623497,
       0.96740047])

In [61]:
logreg.predict_proba(X_train1)[:,1]

array([0.20505418, 0.06535981, 0.07676579, ..., 0.03675358, 0.26376503,
       0.03259953])

**proba of test_inference data**

In [62]:
# probability of getting output as 0 - no rain

logreg.predict_proba(X_test1)[:,0]

array([0.75095553, 0.96271312, 0.72514482, 0.85898183, 0.91063476,
       0.87508725, 0.94915738, 0.1478089 , 0.63481983, 0.98282731,
       0.70497032, 0.82073035, 0.85995755, 0.78684356, 0.52816342,
       0.85526834, 0.94891674, 0.92399821, 0.59823759, 0.65260828,
       0.97682557, 0.9674622 , 0.96811143, 0.96359102, 0.0929378 ,
       0.86699976, 0.81121728, 0.09269823, 0.87223906, 0.94882629,
       0.98566536, 0.9524861 , 0.94499283, 0.87069018, 0.39853768,
       0.56146503, 0.62175049, 0.44690945, 0.56594656, 0.43075234,
       0.91984616, 0.84018599, 0.95750888, 0.45879221, 0.94278717,
       0.97669926, 0.92572633, 0.13296697, 0.80851313, 0.9531593 ,
       0.49092472, 0.92663132, 0.49092472, 0.68410983, 0.75419837,
       0.9675661 , 0.56852866, 0.95633797, 0.98680386, 0.61982581,
       0.71755614, 0.94425803, 0.85578919, 0.944436  , 0.75141882,
       0.91968092, 0.96781185, 0.85606053, 0.92563538, 0.98605156,
       0.46199181, 0.37989781, 0.95998342, 0.40286626, 0.98461

In [63]:
logreg.predict_proba(X_test1)[:,1]

array([0.24904447, 0.03728688, 0.27485518, 0.14101817, 0.08936524,
       0.12491275, 0.05084262, 0.8521911 , 0.36518017, 0.01717269,
       0.29502968, 0.17926965, 0.14004245, 0.21315644, 0.47183658,
       0.14473166, 0.05108326, 0.07600179, 0.40176241, 0.34739172,
       0.02317443, 0.0325378 , 0.03188857, 0.03640898, 0.9070622 ,
       0.13300024, 0.18878272, 0.90730177, 0.12776094, 0.05117371,
       0.01433464, 0.0475139 , 0.05500717, 0.12930982, 0.60146232,
       0.43853497, 0.37824951, 0.55309055, 0.43405344, 0.56924766,
       0.08015384, 0.15981401, 0.04249112, 0.54120779, 0.05721283,
       0.02330074, 0.07427367, 0.86703303, 0.19148687, 0.0468407 ,
       0.50907528, 0.07336868, 0.50907528, 0.31589017, 0.24580163,
       0.0324339 , 0.43147134, 0.04366203, 0.01319614, 0.38017419,
       0.28244386, 0.05574197, 0.14421081, 0.055564  , 0.24858118,
       0.08031908, 0.03218815, 0.14393947, 0.07436462, 0.01394844,
       0.53800819, 0.62010219, 0.04001658, 0.59713374, 0.01538

In [64]:
# from sklearn.metrics import accuracy_score
# print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test1, y_pred_test1)))

In [65]:
# from sklearn.metrics import accuracy_score
# print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_train1, y_pred_train1)))